steps:

# Step 1: Authenticate Docker with Google Container Registry
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo Y | gcloud auth configure-docker gcr.io

# Step 2: Set up the Kubernetes cluster context
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials sumit-cluster --zone asia-south1-c --project sumit-gcp-practice &&
    kubectl version

# Step 3: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/two-tier-app-image', '.']

# Step 4: Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/two-tier-app-image']

# Step 5: Set the image in the Kubernetes deployment
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    kubectl set image deployment/two-tier-app-deployment two-tier-app=gcr.io/$PROJECT_ID/two-tier-app-image:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY




# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/two-tier-app-image:$COMMIT_SHA', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/two-tier-app-image:$COMMIT_SHA']
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       gcloud container clusters get-credentials sumit-cluster \
#         --zone=asia-south1-c
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       kubectl apply -f ./k8s/

# options:
#   substitutionOption: ALLOW_LOOSE
#   logging: CLOUD_LOGGING_ONLY
#   logStreamingOption: STREAM_ON

# substitutions:
#   _DEPLOYMENT_NAME: two-tier-app-deployment
#   _CONTAINER_NAME: two-tier-app-pod
#   _SERVICE_NAME: twotier-app-service
#   _AR_HOSTNAME: asia-docker.pkg.dev
#   _AR_NAME: sumit-gcp-practice
#   _COMMIT_SHA: $COMMIT_SHA

# tags:
# - cicd






# # Define variables
# options:
#   env:
#     - IMAGE_NAME: "twotier-app-image"
#     - DEPLOYMENT_NAME: "two-tier-app-deployment"
#     - CONTAINER_NAME: "two-tier-app-pod"

# steps:
# # Build the Docker image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/$IMAGE_NAME:$COMMIT_SHA', '.']

# # Push the Docker image to Google Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/$IMAGE_NAME:$COMMIT_SHA']

# # Update the Kubernetes deployment with the new image
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['set', 'image', 'deployment/$DEPLOYMENT_NAME', '$CONTAINER_NAME=gcr.io/$PROJECT_ID/$IMAGE_NAME:$COMMIT_SHA']
